LK = ".//p[text()='Личный Кабинет']"
CONSTRUCTOR = ".//p[text()='Конструктор']"
REGISTRATION_LINK = 'Auth_link__1fOlj'
ACCOUNT_BUTTON = 'button_button__33qZ0'
RESTORE_PASSWORD = ".//a[text()='Восстановить пароль']"
PASSWORD_INPUT = "//label[text()='Пароль']/following-sibling::input"
EMAIL_INPUT = "//label[text()='Email']/following-sibling::input"
NAME_INPUT = "//label[text()='Имя']/following-sibling::input"
REGISTRATION_BUTTON = ".//button[text()='Зарегистрироваться']"
ENTER_BUTTON = ".//button[text()='Войти']"
CSS_SELECTOR = "#root > div > header > nav > div > a > svg"
EXIT_BUTTON = "//button[contains(@class, 'Account_button__14Yp3') and text()='Выход']"
AUTH_DIV = "Auth_login__3hAey"
CURRENT_TAB_SELECTOR = ".//div[contains(@class,'tab_tab_type_current')]"
TAB_SELECTOR = ".//div[contains(@class,'tab_tab__1SPyG')]"
BUNS_SELECTOR = ".//span[contains(text(), 'Булки')]"
SAUCE_SELECTOR = ".//span[contains(text(), 'Соусы')]"
INGREDIENTS_SELECTOR = ".//span[contains(text(), 'Начинки')]"
